In [1]:
import pandas as pd
import requests
import numpy as np
from bs4 import BeautifulSoup

#import the libraries

In [2]:
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0] 
df = pd.read_html(str(table))[0]
df.columns = ['Postcode','Borough','Neighbourhood']
df

#create a dataframe with the table from wikipedia

,Postcode,Borough,Neighbourhood
0,M1A,Not assigned,NaN
1,M2A,Not assigned,NaN
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
...,...,...,...
175,M5Z,Not assigned,NaN
176,M6Z,Not assigned,NaN
177,M7Z,Not assigned,NaN
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...
179,M9Z,Not assigned,NaN

In [3]:
#Ignore cells with a borough that is Not assigned

df['Borough']=df['Borough'].replace('Not assigned',np.NaN)
df_toronto=df.dropna()
df_toronto=df_toronto.reset_index(drop=True)
df_toronto

,Postcode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,Regent Park / Harbourfront
3,M6A,North York,Lawrence Manor / Lawrence Heights
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
98,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business reply mail Processing CentrE
101,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
102,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [4]:
#Combine Neighbourhoods with Postcode and Borough
df_toronto=df_toronto.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
df_toronto

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                    Malvern / Rouge
1        M1C  Scarborough           Rouge Hill / Port Union / Highland Creek
2        M1E  Scarborough                Guildwood / Morningside / West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village / St. Phillips / Martin Grov...
101      M9V    Etobicoke  South Steeles / Silverstone / Humbergate / Jam...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [5]:
#Assign Borough values where value is not assigned
df_toronto.loc[df_toronto['Neighbourhood']=='Not assigned','Neighbourhood']=df_toronto['Borough']
df_toronto

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                    Malvern / Rouge
1        M1C  Scarborough           Rouge Hill / Port Union / Highland Creek
2        M1E  Scarborough                Guildwood / Morningside / West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village / St. Phillips / Martin Grov...
101      M9V    Etobicoke  South Steeles / Silverstone / Humbergate / Jam...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [6]:
df_toronto.shape  #show the number of rows

(103, 3)